"use client";

import { useEffect, useState } from "react";
import { supabase } from "../../lib/supabase";
import styles from "../exams/Exams.module.css";

type Option={id:string;text:string;order:number};
type Media={id:string;kind:"image"|"video"|"audio";bucket:string;path:string;url:string|null;alt:string;caption:string|null;transcript:string|null;show_controls:boolean};
type Question={question_id:string;question_text:string;scenario_context:string|null;display_order:number;options:Option[];media:Media[]};

export default function ExamPage(){
 const [attempt,setAttempt]=useState("");const [questions,setQuestions]=useState<Question[]>([]);const [answers,setAnswers]=useState<Record<string,string>>({});const [index,setIndex]=useState(0);const [message,setMessage]=useState("");const [score,setScore]=useState<number|null>(null);const [busy,setBusy]=useState(false);
 useEffect(()=>{const id=new URLSearchParams(window.location.search).get("attempt")||"";setAttempt(id);if(!id){window.location.replace("/exams");return}(async()=>{const {data,error}=await supabase.rpc("get_exam_questions",{attempt_uuid:id});if(error)return setMessage(error.message);const rows=(data??[]) as Question[];for(const q of rows)for(const m of q.media||[])if(m.bucket==="exam-media"){const {data:signed}=await supabase.storage.from(m.bucket).createSignedUrl(m.path,3600);m.url=signed?.signedUrl||null;}setQuestions(rows)})()},[]);
 async function submit(){if(Object.keys(answers).length!==questions.length&&!window.confirm("Some questions are unanswered. Submit anyway?"))return;setBusy(true);const submitted_answers=Object.entries(answers).map(([question_id,option_id])=>({question_id,option_id}));const {data,error}=await supabase.rpc("submit_exam_attempt",{attempt_uuid:attempt,submitted_answers});if(error)setMessage(error.message);else setScore(Number(data));setBusy(false)}
 if(score!==null)return <main className={styles.page}><section className={styles.hero}><small>EXAM SUBMITTED</small><h1>Your score is <em>{score}%</em></h1><p>{score>=70?"Your result has been sent to an administrator for certificate review.":"Your attempt has been recorded. Continue practising and try again when eligible."}</p><a href="/exams" style={{color:"white"}}>Return to exam centre →</a></section></main>;
 const q=questions[index];return <main className={styles.page}><header><a href="/exams"><img src="/logo.jpg" alt=""/><span><b>FUTURE MIND</b><small>SECURE EXAM</small></span></a><nav><span>{questions.length?`Question ${index+1} of ${questions.length}`:"Loading"}</span></nav></header><section className={styles.content}>{message&&<div className={styles.message}>{message}</div>}{q?<article style={{maxWidth:780,margin:"30px auto",background:"white",padding:35,border:"1px solid #dfe3e5"}}><small>QUESTION {index+1}</small>{q.scenario_context&&<p>{q.scenario_context}</p>}{(q.media||[]).map(m=><figure key={m.id} style={{margin:"24px 0"}}>{m.url&&(m.kind==="image"?<img src={m.url} alt={m.alt} style={{width:"100%",maxHeight:460,objectFit:"contain"}}/>:m.kind==="video"?<video src={m.url} controls={m.show_controls} playsInline aria-label={m.alt} style={{width:"100%",maxHeight:460}}/>:<audio src={m.url} controls aria-label={m.alt} style={{width:"100%"}}/>)}{m.caption&&<figcaption>{m.caption}</figcaption>}{m.transcript&&<details><summary>Media transcript</summary><p>{m.transcript}</p></details>}</figure>)}<h1 style={{fontFamily:"Georgia,serif",fontSize:30}}>{q.question_text}</h1><div style={{display:"grid",gap:10,margin:"30px 0"}}>{q.options.map(o=><label key={o.id} style={{border:answers[q.question_id]===o.id?"2px solid #16cbd5":"1px solid #d9e0e5",padding:15,cursor:"pointer"}}><input type="radio" name={q.question_id} checked={answers[q.question_id]===o.id} onChange={()=>setAnswers({...answers,[q.question_id]:o.id})}/> {o.text}</label>)}</div><div style={{display:"flex",justifyContent:"space-between"}}><button disabled={index===0} onClick={()=>setIndex(index-1)}>← Previous</button>{index<questions.length-1?<button onClick={()=>setIndex(index+1)}>Next →</button>:<button disabled={busy} onClick={submit}>{busy?"Submitting…":"Submit exam"}</button>}</div></article>:<div className={styles.empty}>Loading secure exam questions…</div>}</section></main>
}
