"use client";

import { useEffect, useMemo, useState } from "react";
import { supabase } from "../../../lib/supabase";
import styles from "./Studio.module.css";

type Theme={id:string;theme_name:string;primary_color:string;secondary_color:string;accent_color:string;background_color:string;surface_color:string;text_color:string;muted_text_color:string;menu_text_color:string;heading_font:string;body_font:string;base_font_size:number;heading_scale:number;line_height:number;letter_spacing:number;content_width:number;section_spacing:number;button_radius:number;card_radius:number};
type Nav={id:string;label:string;href:string;location:string;display_order:number;is_active:boolean;open_new_tab:boolean};
type Footer={id:string;description:string;badge_text:string;copyright_text:string;contact_email:string|null;social_links:Record<string,string>;is_visible:boolean};
type Section={id:string;section_key:string;display_name:string;display_order:number;is_visible:boolean;background_color:string|null;content:Record<string,string>};
type Media={id:string;name:string;kind:string;bucket:string;storage_path:string;public_url:string|null;alt_text:string|null;caption:string|null;transcript:string|null;mime_type:string;size_bytes:number;archived_at:string|null};
type Popup={id:string;title:string;body_text:string|null;media_asset_id:string|null;button_text:string|null;button_url:string|null;status:string;audience:string;pages:string[];starts_at:string|null;ends_at:string|null;frequency:string;delay_seconds:number;position:string;allow_close:boolean;is_mobile_enabled:boolean;is_desktop_enabled:boolean;priority:number};
type Version={id:string;label:string;snapshot:any;created_at:string};
const tabs=["Theme & Type","Header & Menu","Footer","Page Sections","Media Library","Popups","Versions"];
const fonts=["Geist","Arial","Georgia","Verdana","Trebuchet MS","Times New Roman"];
function contrast(hex1:string,hex2:string){const lum=(h:string)=>{const rgb=(h.replace("#","").match(/.{2}/g)||["00","00","00"]).map(x=>parseInt(x,16)/255).map(x=>x<=.03928?x/12.92:Math.pow((x+.055)/1.055,2.4));return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]};const [a,b]=[lum(hex1),lum(hex2)].sort((x,y)=>y-x);return (a+.05)/(b+.05)}

export default function Studio(){
 const [tab,setTab]=useState(tabs[0]);const [theme,setTheme]=useState<Theme|null>(null);const [nav,setNav]=useState<Nav[]>([]);const [footer,setFooter]=useState<Footer|null>(null);const [sections,setSections]=useState<Section[]>([]);const [media,setMedia]=useState<Media[]>([]);const [popups,setPopups]=useState<Popup[]>([]);const [versions,setVersions]=useState<Version[]>([]);const [notice,setNotice]=useState("");const [busy,setBusy]=useState(false);
 const [navForm,setNavForm]=useState({label:"",href:"#",location:"header"});const [popupForm,setPopupForm]=useState({title:"",body_text:"",media_asset_id:"",button_text:"",button_url:"",audience:"everyone",frequency:"once_session",delay_seconds:2,position:"center",starts_at:"",ends_at:""});const [uploadBucket,setUploadBucket]=useState("site-media");const [uploadAlt,setUploadAlt]=useState("");
 function flash(x:string){setNotice(x);setTimeout(()=>setNotice(""),3000)}
 async function load(){const {data:{user}}=await supabase.auth.getUser();if(!user){location.href="/admin/login";return}const {data:p}=await supabase.from("profiles").select("role").eq("id",user.id).single();if(p?.role!=="admin"){location.href="/admin";return}const [t,n,f,s,m,pop,v]=await Promise.all([supabase.from("site_theme").select("*").single(),supabase.from("navigation_items").select("*").order("display_order"),supabase.from("footer_settings").select("*").single(),supabase.from("page_sections").select("*").order("display_order"),supabase.from("media_assets").select("*").is("archived_at",null).order("created_at",{ascending:false}),supabase.from("popups").select("*").order("priority",{ascending:false}),supabase.from("design_versions").select("*").order("created_at",{ascending:false})]);setTheme(t.data as Theme);setNav((n.data||[]) as Nav[]);setFooter(f.data as Footer);setSections((s.data||[]) as Section[]);setMedia((m.data||[]) as Media[]);setPopups((pop.data||[]) as Popup[]);setVersions((v.data||[]) as Version[])}
 useEffect(()=>{load()},[]);
 async function snapshot(label:string){const {data:{user}}=await supabase.auth.getUser();return supabase.from("design_versions").insert({label,snapshot:{theme,nav,footer,sections},created_by:user?.id})}
 async function saveTheme(){if(!theme)return;if(contrast(theme.text_color,theme.background_color)<4.5)return flash("Text and background contrast is too low. Choose safer colours.");setBusy(true);await snapshot(`Before theme update ${new Date().toLocaleString()}`);const {error}=await supabase.from("site_theme").update({...theme,updated_at:new Date().toISOString()}).eq("id",theme.id);setBusy(false);flash(error?.message||"Theme published safely");load()}
 async function addNav(e:React.FormEvent){e.preventDefault();const {error}=await supabase.from("navigation_items").insert({...navForm,display_order:nav.length+1});flash(error?.message||"Menu item added");setNavForm({label:"",href:"#",location:"header"});load()}
 async function patchNav(item:Nav,patch:Partial<Nav>){await supabase.from("navigation_items").update(patch).eq("id",item.id);load()}
 async function saveFooter(){if(!footer)return;await snapshot("Before footer update");const {error}=await supabase.from("footer_settings").update(footer).eq("id",footer.id);flash(error?.message||"Footer updated");load()}
 async function patchSection(item:Section,patch:Partial<Section>){await snapshot(`Before ${item.display_name} update`);const {error}=await supabase.from("page_sections").update(patch).eq("id",item.id);flash(error?.message||"Section updated");load()}
 async function moveSection(item:Section,delta:number){const target=sections.find(x=>x.display_order===item.display_order+delta);if(!target)return;await supabase.from("page_sections").update({display_order:target.display_order}).eq("id",item.id);await supabase.from("page_sections").update({display_order:item.display_order}).eq("id",target.id);load()}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;if(file.size>52428800)return flash("File exceeds the 50 MB safety limit.");if(file.type.startsWith("image/")&&!uploadAlt.trim())return flash("Alternative text is required for images and animations.");setBusy(true);const kind=file.type.includes("gif")?"animation":file.type.split("/")[0];const path=`${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const {error}=await supabase.storage.from(uploadBucket).upload(path,file,{upsert:false,contentType:file.type});if(error){setBusy(false);return flash(error.message)}const public_url=uploadBucket==="site-media"?supabase.storage.from(uploadBucket).getPublicUrl(path).data.publicUrl:null;const {data:{user}}=await supabase.auth.getUser();const {error:metaError}=await supabase.from("media_assets").insert({name:file.name,kind,bucket:uploadBucket,storage_path:path,public_url,mime_type:file.type,size_bytes:file.size,alt_text:uploadAlt||null,created_by:user?.id});setBusy(false);flash(metaError?.message||"Media uploaded");setUploadAlt("");load()}
 async function archiveMedia(item:Media){if(!confirm(`Archive ${item.name}? Existing content will keep its reference.`))return;await supabase.from("media_assets").update({archived_at:new Date().toISOString()}).eq("id",item.id);flash("Media archived");load()}
 async function createPopup(e:React.FormEvent){e.preventDefault();const {data:{user}}=await supabase.auth.getUser();const {error}=await supabase.from("popups").insert({...popupForm,media_asset_id:popupForm.media_asset_id||null,button_text:popupForm.button_text||null,button_url:popupForm.button_url||null,starts_at:popupForm.starts_at?new Date(popupForm.starts_at).toISOString():null,ends_at:popupForm.ends_at?new Date(popupForm.ends_at).toISOString():null,pages:["/"],created_by:user?.id,status:"draft"});flash(error?.message||"Popup saved as draft");load()}
 async function patchPopup(item:Popup,patch:Partial<Popup>){const {error}=await supabase.from("popups").update(patch).eq("id",item.id);flash(error?.message||"Popup updated");load()}
 async function restore(v:Version){if(!confirm(`Restore design version “${v.label}”?`))return;const s=v.snapshot;if(s.theme)await supabase.from("site_theme").update(s.theme).eq("id",s.theme.id);if(s.footer)await supabase.from("footer_settings").update(s.footer).eq("id",s.footer.id);for(const x of s.nav||[])await supabase.from("navigation_items").update(x).eq("id",x.id);for(const x of s.sections||[])await supabase.from("page_sections").update(x).eq("id",x.id);flash("Design version restored");load()}
 const ratio=useMemo(()=>theme?contrast(theme.text_color,theme.background_color):0,[theme]);
 return <main className={styles.page}><aside><a href="/admin">← Admin dashboard</a><h1>Website Studio</h1><p>Design, media and publishing controls</p><nav>{tabs.map(x=><button className={tab===x?styles.active:""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</nav><a href="/" target="_blank">Open website preview ↗</a></aside><section className={styles.main}><header><div><small>FUTURE MIND GLOBAL</small><h2>{tab}</h2></div><span>{notice||"Changes use safe ranges and version history"}</span></header><div className={styles.content}>
 {tab==="Theme & Type"&&theme&&<><Title title="Theme, colour and typography" text="Control the visual system while preserving readable mobile layouts."/><div className={styles.preview} style={{background:theme.background_color,color:theme.text_color,fontFamily:theme.body_font,borderRadius:theme.card_radius}}><small style={{color:theme.accent_color}}>LIVE PREVIEW</small><h3 style={{fontFamily:theme.heading_font,fontSize:`${theme.heading_scale*24}px`}}>Think beyond borders.</h3><p>Accessible typography and colour preview.</p><button style={{background:theme.accent_color,color:theme.primary_color,borderRadius:theme.button_radius}}>Primary action</button></div><div className={styles.formGrid}>{([['Primary','primary_color'],['Secondary','secondary_color'],['Accent','accent_color'],['Background','background_color'],['Surface','surface_color'],['Text','text_color'],['Muted text','muted_text_color'],['Menu text','menu_text_color']] as const).map(([label,key])=><label key={key}>{label}<input type="color" value={theme[key] as string} onChange={e=>setTheme({...theme,[key]:e.target.value})}/><code>{theme[key]}</code></label>)}<label>Heading font<select value={theme.heading_font} onChange={e=>setTheme({...theme,heading_font:e.target.value})}>{fonts.map(x=><option key={x}>{x}</option>)}</select></label><label>Body font<select value={theme.body_font} onChange={e=>setTheme({...theme,body_font:e.target.value})}>{fonts.map(x=><option key={x}>{x}</option>)}</select></label>{([['Base text size','base_font_size',14,20],['Heading scale','heading_scale',1.2,2.2],['Line height','line_height',1.2,2],['Letter spacing','letter_spacing',-.05,.2],['Content width','content_width',900,1600],['Section spacing','section_spacing',48,180],['Button radius','button_radius',0,40],['Card radius','card_radius',0,40]] as const).map(([label,key,min,max])=><label key={key}>{label}<input type="number" step={(key.includes('scale')||key.includes('height')||key.includes('spacing')) ? 0.01 : 1} min={min} max={max} value={theme[key] as number} onChange={e=>setTheme({...theme,[key]:+e.target.value})}/></label>)}</div><div className={ratio>=4.5?styles.good:styles.bad}>Contrast ratio {ratio.toFixed(2)}:1 — {ratio>=4.5?"WCAG AA pass":"Choose higher-contrast colours"}</div><button className={styles.primary} disabled={busy} onClick={saveTheme}>Preview checked — publish theme</button></>}
 {tab==="Header & Menu"&&<><Title title="Header and menu" text="Add, rename, reorder, hide or redirect navigation items."/><form className={styles.inlineForm} onSubmit={addNav}><input required placeholder="Menu label" value={navForm.label} onChange={e=>setNavForm({...navForm,label:e.target.value})}/><input required placeholder="Link or #section" value={navForm.href} onChange={e=>setNavForm({...navForm,href:e.target.value})}/><select value={navForm.location} onChange={e=>setNavForm({...navForm,location:e.target.value})}><option>header</option><option>footer</option></select><button>Add menu item</button></form><div className={styles.list}>{nav.map((x,i)=><article key={x.id}><span>{i+1}</span><input value={x.label} onChange={e=>setNav(nav.map(n=>n.id===x.id?{...n,label:e.target.value}:n))} onBlur={()=>patchNav(x,{label:nav.find(n=>n.id===x.id)?.label})}/><input value={x.href} onChange={e=>setNav(nav.map(n=>n.id===x.id?{...n,href:e.target.value}:n))} onBlur={()=>patchNav(x,{href:nav.find(n=>n.id===x.id)?.href})}/><button onClick={()=>patchNav(x,{is_active:!x.is_active})}>{x.is_active?"Visible":"Hidden"}</button></article>)}</div></>}
 {tab==="Footer"&&footer&&<><Title title="Footer manager" text="Edit footer copy, contact information, links and visibility."/><div className={styles.stack}><label>Description<textarea value={footer.description} onChange={e=>setFooter({...footer,description:e.target.value})}/></label><label>Badge text<input value={footer.badge_text} onChange={e=>setFooter({...footer,badge_text:e.target.value})}/></label><label>Copyright<input value={footer.copyright_text} onChange={e=>setFooter({...footer,copyright_text:e.target.value})}/></label><label>Contact email<input type="email" value={footer.contact_email||""} onChange={e=>setFooter({...footer,contact_email:e.target.value})}/></label><label><input type="checkbox" checked={footer.is_visible} onChange={e=>setFooter({...footer,is_visible:e.target.checked})}/> Show footer</label><button className={styles.primary} onClick={saveFooter}>Save footer</button></div></>}
 {tab==="Page Sections"&&<><Title title="Pages and sections" text="Reorder, hide, recolour and override the main heading or supporting text."/><div className={styles.list}>{sections.map((x,i)=><article className={styles.sectionRow} key={x.id}><span>{x.display_order}</span><div><b>{x.display_name}</b><small>#{x.section_key}</small></div><input placeholder="Heading override" value={x.content?.title||""} onChange={e=>setSections(sections.map(s=>s.id===x.id?{...s,content:{...s.content,title:e.target.value}}:s))} onBlur={()=>patchSection(x,{content:sections.find(s=>s.id===x.id)?.content})}/><input type="color" value={x.background_color||"#ffffff"} onChange={e=>patchSection(x,{background_color:e.target.value})}/><button onClick={()=>moveSection(x,-1)}>↑</button><button onClick={()=>moveSection(x,1)}>↓</button><button onClick={()=>patchSection(x,{is_visible:!x.is_visible})}>{x.is_visible?"Shown":"Hidden"}</button></article>)}</div></>}
 {tab==="Media Library"&&<><Title title="Media library" text="Upload optimized public site media or protected examination media up to 50 MB."/><div className={styles.upload}><select value={uploadBucket} onChange={e=>setUploadBucket(e.target.value)}><option value="site-media">Public website media</option><option value="exam-media">Protected exam media</option></select><input placeholder="Alternative text (required for images)" value={uploadAlt} onChange={e=>setUploadAlt(e.target.value)}/><input type="file" accept="image/jpeg,image/png,image/webp,image/gif,video/mp4,video/webm,audio/mpeg,audio/wav,audio/ogg" onChange={upload}/></div><div className={styles.mediaGrid}>{media.map(x=><article key={x.id}>{x.public_url&&x.kind==="image"?<img src={x.public_url} alt={x.alt_text||""}/>:x.public_url&&x.kind==="animation"?<img src={x.public_url} alt={x.alt_text||""}/>:x.public_url&&x.kind==="video"?<video src={x.public_url} controls/>:x.public_url&&x.kind==="audio"?<audio src={x.public_url} controls/>:<div className={styles.protected}>Protected {x.kind}</div>}<b>{x.name}</b><small>{x.bucket} · {(x.size_bytes/1024/1024).toFixed(1)} MB</small><p>{x.alt_text||x.caption||"No description"}</p><button onClick={()=>archiveMedia(x)}>Archive</button></article>)}</div></>}
 {tab==="Popups"&&<><Title title="Popup and announcement manager" text="Create poster, image, animation or video announcements with scheduling and audience controls."/><form className={styles.popupForm} onSubmit={createPopup}><input required placeholder="Popup title" value={popupForm.title} onChange={e=>setPopupForm({...popupForm,title:e.target.value})}/><textarea placeholder="Message" value={popupForm.body_text} onChange={e=>setPopupForm({...popupForm,body_text:e.target.value})}/><select value={popupForm.media_asset_id} onChange={e=>setPopupForm({...popupForm,media_asset_id:e.target.value})}><option value="">No media</option>{media.filter(x=>x.bucket==="site-media").map(x=><option value={x.id} key={x.id}>{x.name}</option>)}</select><input placeholder="Button text" value={popupForm.button_text} onChange={e=>setPopupForm({...popupForm,button_text:e.target.value})}/><input placeholder="Button link" value={popupForm.button_url} onChange={e=>setPopupForm({...popupForm,button_url:e.target.value})}/><select value={popupForm.audience} onChange={e=>setPopupForm({...popupForm,audience:e.target.value})}><option>everyone</option><option>visitors</option><option>students</option><option>staff</option></select><select value={popupForm.frequency} onChange={e=>setPopupForm({...popupForm,frequency:e.target.value})}><option>once_session</option><option>once_day</option><option>every_visit</option></select><select value={popupForm.position} onChange={e=>setPopupForm({...popupForm,position:e.target.value})}><option>center</option><option>bottom_right</option><option>bottom_banner</option></select><label>Starts<input type="datetime-local" value={popupForm.starts_at} onChange={e=>setPopupForm({...popupForm,starts_at:e.target.value})}/></label><label>Ends<input type="datetime-local" value={popupForm.ends_at} onChange={e=>setPopupForm({...popupForm,ends_at:e.target.value})}/></label><button>Save popup draft</button></form><div className={styles.list}>{popups.map(x=><article key={x.id}><div><b>{x.title}</b><small>{x.audience} · {x.frequency} · {x.position}</small></div><span className={styles.pill}>{x.status}</span><button onClick={()=>patchPopup(x,{status:x.status==="published"?"draft":"published"})}>{x.status==="published"?"Hide":"Publish"}</button></article>)}</div></>}
 {tab==="Versions"&&<><Title title="Preview, version history and rollback" text="Every major design change creates a restorable snapshot."/><button className={styles.primary} onClick={()=>snapshot(`Manual snapshot ${new Date().toLocaleString()}`).then(()=>{flash("Snapshot saved");load()})}>Create snapshot now</button><div className={styles.list}>{versions.map(x=><article key={x.id}><div><b>{x.label}</b><small>{new Date(x.created_at).toLocaleString()}</small></div><button onClick={()=>restore(x)}>Restore this version</button></article>)}</div></>}
 </div></section>{notice&&<div className={styles.toast}>{notice}</div>}</main>
}
function Title({title,text}:{title:string;text:string}){return <div className={styles.title}><small>SAFE CONTENT MANAGEMENT</small><h3>{title}</h3><p>{text}</p></div>}
