"use client";

import { useEffect, useState } from "react";
import type { User } from "@supabase/supabase-js";
import { supabase } from "../../lib/supabase";
import styles from "./Exams.module.css";

type Exam={id:string;title:string;description:string;pathway:string;time_limit_minutes:number;pass_percentage:number;opens_at:string|null;closes_at:string|null;requires_enrollment:boolean;fixed_finish:boolean;maximum_attempts:number};
type Enrollment={quiz_id:string;status:string};
type Attempt={quiz_id:string;status:string;expires_at:string};
type Certificate={id:string;quiz_title:string;score:number;level:string;verification_code:string;issued_at:string};

export default function ExamsPage(){
  const [user,setUser]=useState<User|null>(null);const [exams,setExams]=useState<Exam[]>([]);const [enrollments,setEnrollments]=useState<Enrollment[]>([]);const [attempts,setAttempts]=useState<Attempt[]>([]);const [certificates,setCertificates]=useState<Certificate[]>([]);const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");
  async function load(userId:string){const [e,en,a,c]=await Promise.all([supabase.from("quizzes").select("id,title,description,pathway,time_limit_minutes,pass_percentage,opens_at,closes_at,requires_enrollment,fixed_finish,maximum_attempts").eq("status","published").order("opens_at"),supabase.from("exam_enrollments").select("quiz_id,status").eq("participant_id",userId),supabase.from("quiz_attempts").select("quiz_id,status,expires_at").eq("participant_id",userId),supabase.from("certificates").select("id,quiz_title,score,level,verification_code,issued_at").eq("participant_id",userId).order("issued_at",{ascending:false})]);setExams((e.data??[]) as Exam[]);setEnrollments((en.data??[]) as Enrollment[]);setAttempts((a.data??[]) as Attempt[]);setCertificates((c.data??[]) as Certificate[]);setLoading(false)}
  useEffect(()=>{supabase.auth.getUser().then(({data})=>{if(!data.user){window.location.replace("/admin/login?next=/exams");return}setUser(data.user);load(data.user.id)})},[]);
  async function request(examId:string){if(!user)return;const {error}=await supabase.from("exam_enrollments").insert({quiz_id:examId,participant_id:user.id});setMessage(error?error.message:"Your enrolment request was sent for approval.");load(user.id)}
  async function start(examId:string){const {data,error}=await supabase.rpc("start_exam",{exam_id:examId});if(error)setMessage(error.message);else window.location.href=`/exam?attempt=${data}`}
  async function signOut(){await supabase.auth.signOut();window.location.href="/"}
  function state(exam:Exam){const enrollment=enrollments.find(e=>e.quiz_id===exam.id);if(exam.requires_enrollment)return enrollment?.status||"not_requested";return "available"}
  return <main className={styles.page}><header><a href="/"><img src="/logo.jpg" alt="Future Mind Global"/><span><b>FUTURE MIND</b><small>STUDENT EXAM CENTRE</small></span></a><nav><span>{user?.email}</span><button onClick={signOut}>Sign out</button></nav></header><section className={styles.hero}><small>YOUR LEARNING JOURNEY</small><h1>Practice. Prepare. <em>Prove your potential.</em></h1><p>Sign in, request access when required, and attend approved Future Mind examinations.</p></section><section className={styles.content}>{message&&<div className={styles.message}>{message}</div>}<div className={styles.heading}><div><small>AVAILABLE NOW</small><h2>Exams and practice</h2></div><span>Times shown in your local timezone</span></div>{loading?<div className={styles.empty}>Loading your exam access…</div>:<div className={styles.cards}>{exams.map(exam=>{const access=state(exam);const resumable=attempts.some(a=>a.quiz_id===exam.id&&a.status==="in_progress"&&new Date(a.expires_at)>new Date());return <article key={exam.id}><div className={styles.cardTop}><span>{exam.pathway.replaceAll("_"," ")}</span><b>{access.replaceAll("_"," ")}</b></div><h3>{exam.title}</h3><p>{exam.description||"A Future Mind Global knowledge and capability assessment."}</p><dl><div><dt>Duration</dt><dd>{exam.time_limit_minutes} minutes</dd></div><div><dt>Pass score</dt><dd>{exam.pass_percentage}%</dd></div><div><dt>Attempts allowed</dt><dd>{exam.maximum_attempts}</dd></div><div><dt>Starts</dt><dd>{exam.opens_at?new Date(exam.opens_at).toLocaleString():"Available now"}</dd></div><div><dt>Finish</dt><dd>{exam.fixed_finish?"Same time for everyone":"Your own timer"}</dd></div></dl>{access==="available"||access==="approved"?<button onClick={()=>start(exam.id)}>{resumable?"Resume exam":"Start exam"} →</button>:access==="not_requested"?<button onClick={()=>request(exam.id)}>Request enrolment</button>:<button disabled>{access==="pending"?"Waiting for admin approval":"Access not approved"}</button>}</article>})}{!exams.length&&<div className={styles.empty}>There are no published exams at this time.</div>}</div>}<div className={styles.heading}><div><small>ACHIEVEMENTS</small><h2>Your certificates</h2></div></div><div className={styles.certificates}>{certificates.map(c=><article key={c.id}><span>◇</span><div><b>{c.quiz_title}</b><small>{c.level} · Score {c.score}% · {new Date(c.issued_at).toLocaleDateString()}</small><code>{c.verification_code}</code></div></article>)}{!certificates.length&&<div className={styles.empty}>Approved certificates will appear here.</div>}</div></section></main>
}
